"""
MODULE: Automated Report Generation.

Direct response to BOT's recommendation: "automate the system for generating
their reports." Compiles the same real, queried figures already shown on the
Internal Dashboard (KPIs, hazard exposure, combined climate-financial
exposure, recent Risk Advisory Reports) into a single formatted PDF, instead
of an analyst manually copying numbers between screens and a document.

Consistent with this project's honesty rules: every figure in the report
comes directly from analytics_service (the same functions the dashboard
uses) - nothing here is invented or separately computed.
"""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak,
)
from sqlalchemy.orm import Session

from app.models.models import RiskAdvisoryNote, User
from app.services import analytics_service

NAVY = colors.HexColor("#12395B")
NAVY_DARK = colors.HexColor("#0A2038")
ACCENT = colors.HexColor("#0FA47F")
LIGHT_GREY = colors.HexColor("#F4F6F8")


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="ReportTitle", fontName="Helvetica-Bold", fontSize=20, textColor=NAVY_DARK, spaceAfter=10, leading=24,
    ))
    styles.add(ParagraphStyle(
        name="ReportSubtitle", fontName="Helvetica", fontSize=10, textColor=colors.grey, spaceAfter=18, leading=13,
    ))
    styles.add(ParagraphStyle(
        name="SectionHeading", fontName="Helvetica-Bold", fontSize=13, textColor=NAVY,
        spaceBefore=16, spaceAfter=8,
    ))
    styles.add(ParagraphStyle(
        name="BodyNote", fontName="Helvetica-Oblique", fontSize=8.5, textColor=colors.grey, spaceAfter=10,
    ))
    return styles


def _table(headers: list[str], rows: list[list[str]], col_widths=None) -> Table:
    data = [headers] + rows if rows else [headers, ["No data available" for _ in headers]]
    if not rows:
        # merge the "no data" row visually
        data = [headers, ["No data available"] + [""] * (len(headers) - 1)]
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GREY]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def _fmt_tzs(amount: float) -> str:
    return f"{amount:,.0f} TZS"


def generate_summary_report_pdf(db: Session, generated_by: User) -> bytes:
    styles = _styles()
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=1.8 * cm, rightMargin=1.8 * cm, topMargin=1.8 * cm, bottomMargin=1.8 * cm,
    )
    story = []

    # ---- Header ----
    story.append(Paragraph("Climate Data Repository", styles["ReportTitle"]))
    story.append(Paragraph("Bank of Tanzania — Automated Analytical Summary Report", styles["ReportSubtitle"]))
    story.append(Paragraph(
        f"Generated by {generated_by.full_name} ({generated_by.role.value}) on "
        f"{datetime.utcnow().strftime('%d %B %Y, %H:%M UTC')}",
        styles["BodyNote"],
    ))

    # ---- KPI Summary ----
    kpi = analytics_service.get_kpi_summary(db, institution_id=None)
    story.append(Paragraph("1. Key Performance Indicators (Sector-Wide)", styles["SectionHeading"]))
    story.append(_table(
        ["Metric", "Value"],
        [
            ["Reporting Institutions", str(kpi["total_institutions"])],
            ["Total Submissions", str(kpi["total_submissions"])],
            ["Pending", str(kpi["pending_submissions"])],
            ["Valid", str(kpi["valid_submissions"])],
            ["Invalid", str(kpi["invalid_submissions"])],
            ["Approved", str(kpi["approved_submissions"])],
            ["Rejected", str(kpi["rejected_submissions"])],
            ["Total Borrowers (distinct, active valid records)", str(kpi["total_borrowers"])],
            ["Total Loan Exposure (active, valid records)", _fmt_tzs(kpi["total_loan_exposure_tzs"])],
            ["Total Collateral Value (active, valid records)", _fmt_tzs(kpi["total_collateral_value_tzs"])],
        ],
        col_widths=[10 * cm, 6.5 * cm],
    ))

    # ---- Climate Hazard Exposure ----
    hazard_rows = analytics_service.get_hazard_exposure(db, institution_id=None)
    story.append(Paragraph("2. Climate Hazard Exposure by Region", styles["SectionHeading"]))
    story.append(Paragraph(
        "Loan exposure grouped by region and institution-reported climate hazard.",
        styles["BodyNote"],
    ))
    story.append(_table(
        ["Region", "Hazard", "Loan Exposure", "Records"],
        [[h["region"], h["hazard_type"] or "None", _fmt_tzs(h["exposed_loan_amount_tzs"]), str(h["record_count"])]
         for h in hazard_rows],
        col_widths=[4.5 * cm, 3.5 * cm, 5 * cm, 3.5 * cm],
    ))

    # ---- Combined Climate-Financial Exposure ----
    combined_rows = analytics_service.get_combined_climate_financial_exposure(db, institution_id=None)
    story.append(Paragraph("3. Combined Climate-Financial Exposure", styles["SectionHeading"]))
    story.append(Paragraph(
        "Real meteorological readings joined with real loan/collateral exposure for the same "
        "region and reporting period. A blank climate column means no reading exists for that "
        "region/period — it is never estimated.",
        styles["BodyNote"],
    ))
    story.append(_table(
        ["Region", "Period", "Rainfall", "Temp", "Hazards", "Loan Exposure"],
        [[
            c["region"], c["reporting_period"],
            f"{c['avg_rainfall_mm']} mm" if c["avg_rainfall_mm"] is not None else "—",
            f"{c['avg_temperature_c']}°C" if c["avg_temperature_c"] is not None else "—",
            ", ".join(c["hazard_types_recorded"]) or "—",
            _fmt_tzs(c["total_loan_exposure_tzs"]),
        ] for c in combined_rows],
        col_widths=[3 * cm, 2.3 * cm, 2.2 * cm, 2 * cm, 3.5 * cm, 3.5 * cm],
    ))

    # ---- Recent Risk Advisory Reports ----
    story.append(PageBreak())
    notes = db.query(RiskAdvisoryNote).order_by(RiskAdvisoryNote.created_at.desc()).limit(15).all()
    story.append(Paragraph("4. Recent Risk Advisory Reports", styles["SectionHeading"]))
    story.append(Paragraph(
        "Analyst-authored climate risk assessments. Risk levels and recommendations are the "
        "authoring analyst's own professional judgement, not a system-computed score.",
        styles["BodyNote"],
    ))
    note_rows = []
    for n in notes:
        author = db.query(User).filter(User.id == n.created_by_user_id).first()
        note_rows.append([
            n.title,
            n.region or "All regions",
            n.risk_level.value,
            author.full_name if author else "Analyst",
            n.created_at.strftime("%Y-%m-%d"),
        ])
    story.append(_table(
        ["Title", "Region", "Risk Level", "Author", "Date"],
        note_rows,
        col_widths=[5.5 * cm, 3 * cm, 2.5 * cm, 3.5 * cm, 2.5 * cm],
    ))

    story.append(Spacer(1, 24))
    story.append(Paragraph(
        "This report was generated automatically from live system data. It is an internal "
        "supervisory document — figures reflect the CDR prototype's current dataset, which may "
        "include clearly-labelled synthetic climate data where real TMA/PMO data is not yet "
        "available (see docs/ASSUMPTIONS_AND_LIMITATIONS.md).",
        styles["BodyNote"],
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def generate_summary_report_excel(db: Session, generated_by: User) -> bytes:
    """
    Same figures as the PDF report, as a multi-sheet Excel workbook - useful
    when an analyst wants to filter/pivot the numbers themselves rather than
    just read a formatted document.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment

    wb = Workbook()
    header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
    header_font = Font(color="FFFFFF", bold=True)

    def write_sheet(ws, headers, rows):
        for col_idx, h in enumerate(headers, start=1):
            cell = ws.cell(row=1, column=col_idx, value=h)
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(horizontal="center")
            ws.column_dimensions[cell.column_letter].width = 20
        for row_idx, row in enumerate(rows, start=2):
            for col_idx, value in enumerate(row, start=1):
                ws.cell(row=row_idx, column=col_idx, value=value)

    # ---- KPI Summary ----
    ws1 = wb.active
    ws1.title = "KPI Summary"
    kpi = analytics_service.get_kpi_summary(db, institution_id=None)
    write_sheet(ws1, ["Metric", "Value"], [
        ["Reporting Institutions", kpi["total_institutions"]],
        ["Total Submissions", kpi["total_submissions"]],
        ["Pending", kpi["pending_submissions"]],
        ["Valid", kpi["valid_submissions"]],
        ["Invalid", kpi["invalid_submissions"]],
        ["Approved", kpi["approved_submissions"]],
        ["Rejected", kpi["rejected_submissions"]],
        ["Total Borrowers", kpi["total_borrowers"]],
        ["Total Loan Exposure (TZS)", kpi["total_loan_exposure_tzs"]],
        ["Total Collateral Value (TZS)", kpi["total_collateral_value_tzs"]],
    ])

    # ---- Hazard Exposure ----
    ws2 = wb.create_sheet("Hazard Exposure")
    hazard_rows = analytics_service.get_hazard_exposure(db, institution_id=None)
    write_sheet(ws2, ["Region", "Hazard", "Loan Exposure (TZS)", "Records"], [
        [h["region"], h["hazard_type"] or "None", h["exposed_loan_amount_tzs"], h["record_count"]]
        for h in hazard_rows
    ])

    # ---- Combined Climate-Financial Exposure ----
    ws3 = wb.create_sheet("Combined Exposure")
    combined_rows = analytics_service.get_combined_climate_financial_exposure(db, institution_id=None)
    write_sheet(ws3, ["Region", "Period", "Avg Rainfall (mm)", "Avg Temp (C)", "Hazards", "Loan Exposure (TZS)", "Collateral Value (TZS)", "Records"], [
        [
            c["region"], c["reporting_period"],
            c["avg_rainfall_mm"] if c["avg_rainfall_mm"] is not None else None,
            c["avg_temperature_c"] if c["avg_temperature_c"] is not None else None,
            ", ".join(c["hazard_types_recorded"]),
            c["total_loan_exposure_tzs"], c["total_collateral_value_tzs"], c["record_count"],
        ] for c in combined_rows
    ])

    # ---- Risk Advisory Reports ----
    ws4 = wb.create_sheet("Risk Advisory Reports")
    notes = db.query(RiskAdvisoryNote).order_by(RiskAdvisoryNote.created_at.desc()).all()
    note_rows = []
    for n in notes:
        author = db.query(User).filter(User.id == n.created_by_user_id).first()
        note_rows.append([
            n.title, n.region or "All regions", n.hazard_type or "-", n.risk_level.value,
            author.full_name if author else "Analyst", n.narrative, n.recommendation or "",
            n.created_at.strftime("%Y-%m-%d"),
        ])
    write_sheet(ws4, ["Title", "Region", "Hazard", "Risk Level", "Author", "Narrative", "Recommendation", "Date"], note_rows)
    ws4.column_dimensions["F"].width = 50
    ws4.column_dimensions["G"].width = 40

    info_sheet = wb.create_sheet("About This Export", 0)
    info_sheet["A1"] = "Climate Data Repository - Automated Summary Export"
    info_sheet["A2"] = f"Generated by {generated_by.full_name} ({generated_by.role.value}) on {datetime.utcnow().strftime('%d %B %Y, %H:%M UTC')}"
    info_sheet["A3"] = "Figures may include SYNTHETIC/demo climate data - see docs/ASSUMPTIONS_AND_LIMITATIONS.md"
    info_sheet.column_dimensions["A"].width = 90
    wb.active = 0

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer.read()
