"""initial schema

Revision ID: d2616a6f36ac
Revises: 
Create Date: 2026-09-18 07:30:10.705379
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'd2616a6f36ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('BANK', 'METEOROLOGICAL_AUTHORITY', 'GOVERNMENT_AGENCY', 'OTHER', name='institutiontype'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'BOT_USER', 'INSTITUTION_USER', name='roleenum'), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_institution_id'), 'users', ['institution_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('climate_ingestion_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_accepted', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('records_duplicate', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_ingestion_batches_created_at'), 'climate_ingestion_batches', ['created_at'], unique=False)
    op.create_index('ix_climate_ingestion_batches_source_created', 'climate_ingestion_batches', ['source', 'created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('related_entity_type', sa.String(length=100), nullable=True),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='accessrequeststatus'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_requests_reviewer', 'password_reset_requests', ['reviewed_by_user_id'], unique=False)
    op.create_index('ix_password_reset_requests_user_status', 'password_reset_requests', ['user_id', 'status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('risk_advisory_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('hazard_type', sa.String(length=100), nullable=True),
    sa.Column('reporting_period', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('data_snapshot', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_advisory_notes_created_by', 'risk_advisory_notes', ['created_by_user_id'], unique=False)
    op.create_index('ix_risk_advisory_notes_region_period', 'risk_advisory_notes', ['region', 'reporting_period'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('institution_id', sa.String(), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('reporting_period', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALID', 'INVALID', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='submissionstatus'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('valid_records', sa.Integer(), nullable=True),
    sa.Column('invalid_records', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.String(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("length(reporting_period) = 7 AND substr(reporting_period, 5, 2) = '-Q' AND substr(reporting_period, 7, 1) IN ('1','2','3','4')", name='ck_submissions_reporting_period_format'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_institution_id'), 'submissions', ['institution_id'], unique=False)
    op.create_index('ix_submissions_institution_period_status', 'submissions', ['institution_id', 'reporting_period', 'status'], unique=False)
    op.create_index(op.f('ix_submissions_reporting_period'), 'submissions', ['reporting_period'], unique=False)
    op.create_index('ix_submissions_reviewed_by_user', 'submissions', ['reviewed_by_user_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index('ix_submissions_submitted_by_user', 'submissions', ['submitted_by_user_id'], unique=False)
    op.create_table('climate_ingestion_errors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['climate_ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_climate_ingestion_errors_batch_row', 'climate_ingestion_errors', ['batch_id', 'row_number'], unique=False)
    op.create_table('climate_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('avg_temperature_c', sa.Float(), nullable=True),
    sa.Column('hazard_type', sa.String(length=100), nullable=True),
    sa.Column('hazard_severity', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('temperature_min_c', sa.Float(), nullable=True),
    sa.Column('temperature_max_c', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=True),
    sa.Column('reporting_period', sa.String(length=20), nullable=True),
    sa.Column('period_type', sa.String(length=20), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('dataset_name', sa.String(length=255), nullable=True),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('station_id', sa.String(length=100), nullable=True),
    sa.Column('station_name', sa.String(length=255), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('quality_flag', sa.String(length=30), nullable=True),
    sa.Column('processing_method', sa.String(length=100), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(), nullable=True),
    sa.CheckConstraint("hazard_severity IS NULL OR hazard_severity IN ('LOW','MEDIUM','HIGH')", name='ck_climate_records_hazard_severity'),
    sa.CheckConstraint("period_type IS NULL OR period_type IN ('DAILY','MONTHLY','QUARTERLY','ANNUAL')", name='ck_climate_records_period_type'),
    sa.CheckConstraint("quality_flag IN ('UNVALIDATED','VALIDATED','FLAGGED','SYNTHETIC')", name='ck_climate_records_quality_flag'),
    sa.CheckConstraint('avg_temperature_c IS NULL OR (avg_temperature_c >= -90 AND avg_temperature_c <= 70)', name='ck_climate_records_avg_temperature_plausible'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_climate_records_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_climate_records_longitude'),
    sa.CheckConstraint('month IS NULL OR (month >= 1 AND month <= 12)', name='ck_climate_records_month'),
    sa.CheckConstraint('rainfall_mm IS NULL OR rainfall_mm >= 0', name='ck_climate_records_rainfall_nonnegative'),
    sa.CheckConstraint('temperature_max_c IS NULL OR (temperature_max_c >= -90 AND temperature_max_c <= 70)', name='ck_climate_records_max_temperature_plausible'),
    sa.CheckConstraint('temperature_max_c IS NULL OR avg_temperature_c IS NULL OR avg_temperature_c <= temperature_max_c', name='ck_climate_records_avg_le_max'),
    sa.CheckConstraint('temperature_min_c IS NULL OR (temperature_min_c >= -90 AND temperature_min_c <= 70)', name='ck_climate_records_min_temperature_plausible'),
    sa.CheckConstraint('temperature_min_c IS NULL OR avg_temperature_c IS NULL OR temperature_min_c <= avg_temperature_c', name='ck_climate_records_min_le_avg'),
    sa.CheckConstraint('temperature_min_c IS NULL OR temperature_max_c IS NULL OR temperature_min_c <= temperature_max_c', name='ck_climate_records_min_le_max'),
    sa.ForeignKeyConstraint(['batch_id'], ['climate_ingestion_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_climate_records_batch_id'), 'climate_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_climate_records_observation_date'), 'climate_records', ['observation_date'], unique=False)
    op.create_index('ix_climate_records_observation_identity', 'climate_records', ['region', 'district', 'year', 'month', 'source_record_id', 'station_id'], unique=False)
    op.create_index(op.f('ix_climate_records_region'), 'climate_records', ['region'], unique=False)
    op.create_index('ix_climate_records_region_period_quality', 'climate_records', ['region', 'reporting_period', 'quality_flag'], unique=False)
    op.create_index(op.f('ix_climate_records_reporting_period'), 'climate_records', ['reporting_period'], unique=False)
    op.create_index(op.f('ix_climate_records_source'), 'climate_records', ['source'], unique=False)
    op.create_index(op.f('ix_climate_records_station_id'), 'climate_records', ['station_id'], unique=False)
    op.create_table('submission_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('branch_code', sa.String(length=50), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('client_type', sa.String(length=50), nullable=True),
    sa.Column('business_size', sa.String(length=50), nullable=True),
    sa.Column('annual_turnover_tzs', sa.Float(), nullable=True),
    sa.Column('loan_id', sa.String(length=100), nullable=True),
    sa.Column('disbursement_date', sa.String(length=30), nullable=True),
    sa.Column('maturity_date', sa.String(length=30), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('loan_amount_tzs', sa.Float(), nullable=True),
    sa.Column('outstanding_principal_tzs', sa.Float(), nullable=True),
    sa.Column('annual_interest_rate', sa.Float(), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True),
    sa.Column('loan_economic_activity', sa.String(length=100), nullable=True),
    sa.Column('loan_purpose', sa.String(length=255), nullable=True),
    sa.Column('asset_classification', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=150), nullable=True),
    sa.Column('village', sa.String(length=150), nullable=True),
    sa.Column('loan_latitude', sa.Float(), nullable=True),
    sa.Column('loan_longitude', sa.Float(), nullable=True),
    sa.Column('collateral_type', sa.String(length=150), nullable=True),
    sa.Column('collateral_pledged_date', sa.String(length=30), nullable=True),
    sa.Column('collateral_value_tzs', sa.Float(), nullable=True),
    sa.Column('collateral_forced_sale_value_tzs', sa.Float(), nullable=True),
    sa.Column('collateral_economic_activity', sa.String(length=100), nullable=True),
    sa.Column('collateral_region', sa.String(length=100), nullable=True),
    sa.Column('collateral_district', sa.String(length=100), nullable=True),
    sa.Column('collateral_ward', sa.String(length=150), nullable=True),
    sa.Column('collateral_village', sa.String(length=150), nullable=True),
    sa.Column('collateral_latitude', sa.Float(), nullable=True),
    sa.Column('collateral_longitude', sa.Float(), nullable=True),
    sa.Column('insurance_coverage', sa.String(length=10), nullable=True),
    sa.Column('insurance_policy_type', sa.String(length=150), nullable=True),
    sa.Column('insurance_provider_name', sa.String(length=255), nullable=True),
    sa.Column('insurance_value_protected_tzs', sa.Float(), nullable=True),
    sa.Column('borrower_name', sa.String(length=255), nullable=True),
    sa.Column('climate_hazard_exposure', sa.String(length=100), nullable=True),
    sa.CheckConstraint('annual_interest_rate IS NULL OR (annual_interest_rate >= 0 AND annual_interest_rate <= 100)', name='ck_submission_records_interest_rate'),
    sa.CheckConstraint('annual_turnover_tzs IS NULL OR annual_turnover_tzs >= 0', name='ck_submission_records_turnover_nonnegative'),
    sa.CheckConstraint('collateral_forced_sale_value_tzs IS NULL OR collateral_forced_sale_value_tzs >= 0', name='ck_submission_records_forced_sale_nonnegative'),
    sa.CheckConstraint('collateral_latitude IS NULL OR (collateral_latitude >= -90 AND collateral_latitude <= 90)', name='ck_submission_records_collateral_latitude'),
    sa.CheckConstraint('collateral_longitude IS NULL OR (collateral_longitude >= -180 AND collateral_longitude <= 180)', name='ck_submission_records_collateral_longitude'),
    sa.CheckConstraint('collateral_value_tzs IS NULL OR collateral_value_tzs >= 0', name='ck_submission_records_collateral_value_nonnegative'),
    sa.CheckConstraint('insurance_value_protected_tzs IS NULL OR insurance_value_protected_tzs >= 0', name='ck_submission_records_insurance_nonnegative'),
    sa.CheckConstraint('loan_amount_tzs IS NULL OR loan_amount_tzs >= 0', name='ck_submission_records_loan_amount_nonnegative'),
    sa.CheckConstraint('loan_latitude IS NULL OR (loan_latitude >= -90 AND loan_latitude <= 90)', name='ck_submission_records_loan_latitude'),
    sa.CheckConstraint('loan_longitude IS NULL OR (loan_longitude >= -180 AND loan_longitude <= 180)', name='ck_submission_records_loan_longitude'),
    sa.CheckConstraint('outstanding_principal_tzs IS NULL OR outstanding_principal_tzs >= 0', name='ck_submission_records_outstanding_nonnegative'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_records_customer_id'), 'submission_records', ['customer_id'], unique=False)
    op.create_index(op.f('ix_submission_records_loan_id'), 'submission_records', ['loan_id'], unique=False)
    op.create_index(op.f('ix_submission_records_region'), 'submission_records', ['region'], unique=False)
    op.create_index('ix_submission_records_submission_loan', 'submission_records', ['submission_id', 'loan_id'], unique=False)
    op.create_index('ix_submission_records_submission_valid_loan', 'submission_records', ['submission_id', 'is_valid', 'loan_id'], unique=False)
    op.create_table('validation_errors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('error_description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_errors_submission', 'validation_errors', ['submission_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validation_errors_submission', table_name='validation_errors')
    op.drop_table('validation_errors')
    op.drop_index('ix_submission_records_submission_valid_loan', table_name='submission_records')
    op.drop_index('ix_submission_records_submission_loan', table_name='submission_records')
    op.drop_index(op.f('ix_submission_records_region'), table_name='submission_records')
    op.drop_index(op.f('ix_submission_records_loan_id'), table_name='submission_records')
    op.drop_index(op.f('ix_submission_records_customer_id'), table_name='submission_records')
    op.drop_table('submission_records')
    op.drop_index(op.f('ix_climate_records_station_id'), table_name='climate_records')
    op.drop_index(op.f('ix_climate_records_source'), table_name='climate_records')
    op.drop_index(op.f('ix_climate_records_reporting_period'), table_name='climate_records')
    op.drop_index('ix_climate_records_region_period_quality', table_name='climate_records')
    op.drop_index(op.f('ix_climate_records_region'), table_name='climate_records')
    op.drop_index('ix_climate_records_observation_identity', table_name='climate_records')
    op.drop_index(op.f('ix_climate_records_observation_date'), table_name='climate_records')
    op.drop_index(op.f('ix_climate_records_batch_id'), table_name='climate_records')
    op.drop_table('climate_records')
    op.drop_index('ix_climate_ingestion_errors_batch_row', table_name='climate_ingestion_errors')
    op.drop_table('climate_ingestion_errors')
    op.drop_index('ix_submissions_submitted_by_user', table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index('ix_submissions_reviewed_by_user', table_name='submissions')
    op.drop_index(op.f('ix_submissions_reporting_period'), table_name='submissions')
    op.drop_index('ix_submissions_institution_period_status', table_name='submissions')
    op.drop_index(op.f('ix_submissions_institution_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_risk_advisory_notes_region_period', table_name='risk_advisory_notes')
    op.drop_index('ix_risk_advisory_notes_created_by', table_name='risk_advisory_notes')
    op.drop_table('risk_advisory_notes')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_password_reset_requests_user_status', table_name='password_reset_requests')
    op.drop_index('ix_password_reset_requests_reviewer', table_name='password_reset_requests')
    op.drop_table('password_reset_requests')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_climate_ingestion_batches_source_created', table_name='climate_ingestion_batches')
    op.drop_index(op.f('ix_climate_ingestion_batches_created_at'), table_name='climate_ingestion_batches')
    op.drop_table('climate_ingestion_batches')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_institution_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
